apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: cs443-snippy_app
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /home/src/app
          name: test-volume
        workingDir: /home/src/app
        command: ["gradle", "bootRun"]
      volumes:
      - name: test-volume
        hostPath:
          path: /run/desktop/mnt/host/wsl/work/app
          type: Directory 
