version: "3.9"
services:
  app:
    build: ./app/
    ports:
      - "8080:8080"
    volumes:
      - ./app:/home/src/app
    working_dir: /home/src/app
    command: gradle bootRun 
    
  auth:
    build: ./auth/
    volumes:
      - ./auth:/home/src/auth
    ports:
      - "8081:8080"
    working_dir: /home/src/auth
    command: gradle bootRun

  analytics:
    build: ./analytics
    volumes:
      - ./analytics:/home/src/analytics
    ports:
      - "8082:8080"
    working_dir: /home/src/analytics
    command: gradle bootRun
