version: "3"
services:

  app:
    build: ./app
    image: app-microservice
    environment:
      - FIRESTORE_EMULATOR_HOST=firestore:8200
      - FIRESTORE_PROJECT_ID=snippy-me-cs443
      - GRADLE_USER_HOME=.my-gradle
    ports:
      - "8089:8080"
    volumes:
      - ./app:/home/src/app
      - ./libs:/home/src/libs
    links:
      - "auth:auth-service"
      - "analytics:analytics-service"
      - "firestore_emulator:firestore"
      - "redis:redis-service"
    working_dir: /home/src/app
    command: sh -c "./gradlew clean --stop && (./gradlew build --continuous | ./gradlew bootRun)"
  auth:
    build: ./auth/
    image: auth-microservice
    environment:
      - FIRESTORE_EMULATOR_HOST=firestore:8200
      - FIRESTORE_PROJECT_ID=snippy-me-cs443
      - GRADLE_USER_HOME=.my-gradle
    volumes:
      - ./auth:/home/src/auth 
      - ./libs:/home/src/libs
    ports: 
      - "8081:8080"
    links:
      - "firestore_emulator:firestore"
    working_dir: /home/src/auth
    command: sh -c "./gradlew clean --stop && (./gradlew build --continuous | ./gradlew bootRun)"
  analytics:
    build: ./analytics
    image: analytics-microservice
    environment:
      - FIRESTORE_EMULATOR_HOST=firestore:8200
      - FIRESTORE_PROJECT_ID=snippy-me-cs443
      - GRADLE_USER_HOME=.my-gradle
    volumes:
      - ./analytics:/home/src/analytics
      - ./libs:/home/src/libs
    ports:
      - "8082:8080"
    links:
      - "firestore_emulator:firestore"
    working_dir: /home/src/analytics
    command: sh -c "./gradlew clean --stop && (./gradlew build --continuous | ./gradlew bootRun)"
  firestore_emulator:
    image: mtlynch/firestore-emulator
    environment:
      - FIRESTORE_PROJECT_ID=snippy-me-cs443
      - PORT=8200
  redis:
    image: redis:latest
    ports:
        - 6379:6379
    volumes:
        - ./config/redis.conf:/redis.conf
    command: [ "redis-server", "/redis.conf" ]
