version: "3"
services:
  firestore_emulator:
    image: mtlynch/firestore-emulator
    environment:
      - FIRESTORE_PROJECT_ID=snippy-me-cs443
      - PORT=8200
  app:
    build: ./app
    image: app-microservice
    environment:
      - FIRESTORE_EMULATOR_HOST=firestore:8200
      - FIRESTORE_PROJECT_ID=snippy-me-cs443
    ports:
      - "8080:8080"
    volumes:
      - ./app:/home/src/app
      - ./.d.env:/home/env
    links:
      - "auth:auth-service"
      - "analytics:analytics-service"
      - "firestore_emulator:firestore"
    working_dir: /home/src/app
    # stdin_open: true # docker run -i
    # tty: true        # docker run -t
    command: sh -c "gradle clean --stop && (gradle build --continuous | gradle bootRun)"
  auth:
    build: ./auth/
    image: auth-microservice
    volumes:
      - ./auth:/home/src/auth
    ports:
      - "8081:8080"
    working_dir: /home/src/auth
    command: sh -c "gradle clean --stop && (gradle build --continuous | gradle bootRun)"
  analytics:
    build: ./analytics
    image: analytics-microservice
    volumes:
      - ./analytics:/home/src/analytics
    ports:
      - "8082:8080"
    working_dir: /home/src/analytics
    command: sh -c "gradle clean --stop && (gradle build --continuous | gradle bootRun)"
