version: "3"
services:
  app:
    build: ./app
    image: app-microservice
    ports:
      - "8089:8080"
    volumes:
      - ./app:/home/src/app
    links:
      - "auth:auth-service"
      - "analytics:analytics-service"
      - "redis:redis-service"
    working_dir: /home/src/app
    # stdin_open: true # docker run -i
    # tty: true        # docker run -t
    command: sh -c "gradle clean --stop && (gradle build --continuous | gradle bootRun)"
  auth:
    build: ./auth/
    image: auth-microservice
    volumes:
      - ./auth:/home/src/auth
    ports: 
      - "8081:8080"
    working_dir: /home/src/auth
    command: sh -c "gradle clean --stop && (gradle build --continuous | gradle bootRun)"
  analytics:
    build: ./analytics
    image: analytics-microservice
    volumes:
      - ./analytics:/home/src/analytics
    ports:
      - "8082:8080"
    working_dir: /home/src/analytics
    command: sh -c "gradle clean --stop && (gradle build --continuous | gradle bootRun)"
  
  redis:
    image: redis:latest
    ports:
        - 6379:6379
    volumes:
        - ./config/redis.conf:/redis.conf
    command: [ "redis-server", "/redis.conf" ]
