version: '3'
services:
  app:
    image: gradle:6.8.3-jdk11 
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/home/env/key.json
      - FIRESTORE_PROJECT_ID=snippy-me-cs443
      - GRADLE_USER_HOME=.my-gradle
    ports:
      - '8089:8080'
    volumes:
      - './core:/home/src/app'
      - './libs:/home/src/libs'
      - './.d.env:/home/env'
    links:
      - 'analytics:analytics-service'
      - 'redis:redis-service'
    working_dir: /home/src/app
    command: sh -c "./gradlew clean --stop && (./gradlew build --continuous | ./gradlew bootRun)"
  analytics:
    image: gradle:6.8.3-jdk11
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/home/env/key.json
      - FIRESTORE_PROJECT_ID=snippy-me-cs443
      - GRADLE_USER_HOME=.my-gradle
    volumes:
      - './analytics:/home/src/analytics'
      - './libs:/home/src/libs'
      - './.d.env:/home/env'
    ports:
      - '8082:8080'
    working_dir: /home/src/analytics
    command: sh -c "./gradlew clean --stop && (./gradlew build --continuous | ./gradlew bootRun )"
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
    volumes:
      - './redis_config/redis.conf:/redis.conf'
    command:
      - redis-server
      - /redis.conf
