version: "3"
services:
  app:
    build: ./app
    image: app-microservice
    ports:
      - "8080:8080"
    volumes:
      - ./app:/home/src/app
    links:
      - "auth:auth"
      - "analytics:analytics"
    working_dir: /home/src/app
    # stdin_open: true # docker run -i
    # tty: true        # docker run -t
    command: gradle bootRun
    
  auth:
    build: ./auth/
    image: auth-microservice
    volumes:
      - ./auth:/home/src/auth
    ports:
      - "8081:8080"
    working_dir: /home/src/auth
    command: gradle bootRun

  analytics:
    build: ./analytics
    image: analytics-microservice
    volumes:
      - ./analytics:/home/src/analytics
    ports:
      - "8082:8080"
    working_dir: /home/src/analytics
    command: gradle bootRun
