version: "3.9"
services:
  app:
    image: springd
    ports:
      - "8080:8080"
    volumes:
      - ./app:/home/app
    working_dir: /home/app
    command: ./gradlew bootRun 
    
  auth:
    image: springd
    volumes:
      - ./auth:/home/app
    ports:
      - "8081:8080"
    working_dir: /home/app
    command: ./gradlew bootRun

  analytics:
    image: springd
    volumes:
      - ./analytics:/home/app
    ports:
      - "8082:8080"
    working_dir: /home/app
    command: ./gradlew bootRun
