apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics
  template:
    metadata:
      labels:
        app: analytics
    spec:
      containers:
      - name: analytics
        image: cs443-snippy_analytics
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /home/src/app
          name: test-volume
        workingDir: /home/src/app
        command: ["gradle", "bootRun"]
      volumes:
      - name: test-volume
        hostPath:
          path: /run/desktop/mnt/host/wsl/work/analytics
          type: Directory 
