apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-deployment
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: analytics
  template:
    metadata:
      labels:
        app: analytics
    spec:
      volumes:
      - name: google-cloud-key
        secret:
          secretName: gauth-key
      containers:
      - name: analytics
        image: eu.gcr.io/snippy-me-cs443/cs443-snippy_analytics:latest
        imagePullPolicy: Always
        volumeMounts:
          - name: google-cloud-key
            mountPath: /home/env
        ports:
        - containerPort: 8080
        workingDir: /home/app
        command: ["java", "-jar", "analytics-0.0.1-SNAPSHOT.jar"]
