apiVersion: v1
kind: Service
metadata:
  name: analytics-service
spec:
  type: LoadBalancer 
  loadBalancerIP: "35.189.115.2"
  selector:
    app: analytics
  ports:
    - protocol: TCP
      port: 8080
