apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      volumes:
      - name: google-cloud-key
        secret:
          secretName: gauth-key
      containers:
      - name: app
        image: eu.gcr.io/snippy-me-cs443/cs443-snippy_app:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "50m"
            memory: "128Mi"
          limits:
            cpu: "100m"
            memory: "256Mi"
        volumeMounts:
          - name: google-cloud-key
            mountPath: /home/env
        ports:
        - containerPort: 8080
        workingDir: /home/app
        command: ["java", "-jar", "core-0.0.1-SNAPSHOT.jar"]
